openslide/openslide.github.io

index.md

We've been rehosting the PDF on `download.openslide.org` because `jpathinformatics.org` requires clicking through a landing page.  However, the PDF is the last user of `download.openslide.org`, and it'd be nice to fully deprecate that service, which is HTTP-only.  We could rehost the PDF in this repo (it's 1.8 MB), but instead take the path of least resistance and link to the official site.

index: link to paper PDF on jpathinformatics.org

---

docs/debugopts/index.md

Added in https://github.com/openslide/openslide/pull/373.

debugopts: document `sql` debug option

---

docs/debugopts/index.md
docs/testsuite/index.md

The test suite added a `dicom` feature flag, and OpenSlide gained a `search` debug option.

docs: document new flags for DICOM format

---

docs/newformat/index.md

For https://github.com/openslide/openslide/pull/435.

doc/newformat: stop using glib slice allocator

---

docs/devguide/index.md

Encourage splitting changes into multiple commits, and rewriting commits in response to PR feedback.  This makes it easier to review changes and maintains a more fine-grained and legible Git history.
Fixes https://github.com/openslide/openslide/issues/196.

docs/devguide: document recommended PR structure and review flow

---

.github/workflows/retile.yml
demo/_synctiles.py

Embed sRGB profile in tiles iff we do a conversion.
Requires OpenSlide Python 1.3.0 to run and OpenSlide 4.0.0 to do any color conversion.

synctiles: convert tiles to sRGB if an ICC profile is available

---

download/index.md

OpenSlide 4.0.0 will not support EL7.  Drop Scientific Linux, which only has EL7, and update the "CentOS" references to "CentOS Stream".

download: support EL8 and above

---

css/custom.css
download/index.md

Make it easier for Ubuntu users to get current versions of OpenSlide and OpenSlide Python.  PPAs don't support Debian, so give Ubuntu its own table row.
Also add several distros and various other cleanups.

download: add Ubuntu PPA, Arch, conda-forge, MSYS2, vcpkg; cleanups

---

demo/_synctiles.py

ICC profiles don't necessarily support all rendering intents, and aren't necessarily optimized for all the intents they do support.  They can also be queried for the rendering intent recommended by the profile creator.  Use that instead of absolute colorimetric.
While we're here, add a friendly name for Philips TIFF.
xref https://github.com/openslide/openslide-python/pull/227

synctiles: use default rendering intent from slide ICC profile

---

_includes/links.md
_includes/news.md
download/index.md

Document the new Copr.  Install the `openslide-tools` subpackage so we get the command-line tools as on other distros.  Use `dnf` because we no longer have a compatibility requirement for `yum`.

Add Copr and clean up package installation on Fedora/EL

---

formats/generic-tiff/index.md

For https://github.com/openslide/openslide/pull/547.

generic-tiff: document support for missing tiles

---

.github/workflows/retile.yml

It's no longer possible for multiple jobs to accumulate results into the same artifact.  Upload a separate artifact for each summary file, and download them all via wildcard.

workflows/retile: update to artifacts v4

---

.github/workflows/retile.yml
.github/workflows/validate.yml
.pre-commit-config.yaml
_config.yml
_testdata/testdata_fetch.py
_testdata/testdata_index.py
css/trac.css
demo/_synctiles.py
demo/index.html
docs/premultiplied-argb/index.md
index.md
license/index.md
pyproject.toml

Read the target S3 bucket name from the `_synctiles.py` command line, and in turn from the `DEMO_TILER_BUCKET` variable of the `demo-site` environment in GitHub Actions.  This allows forks to test code changes on a non-production bucket.

Enable Python pre-commit checks; add more structure to `synctiles`

---

docs/testsuite/index.md

For https://github.com/openslide/openslide/pull/554.

docs/testsuite: remove Valgrind support

---

docs/testsuite/index.md

Partially reverts #75.  For https://github.com/openslide/openslide/pull/555.

docs/testsuite: re-add valgrind command

---

.pre-commit-config.yaml
demo/_synctiles.py

We aren't rethrowing the `BaseException` because we're returning it to a different thread instead.

synctiles: silence spurious warning with current flake8-bugbear

---

docs/debugopts/index.md
docs/testsuite/index.md

For https://github.com/openslide/openslide/pull/569.

Document `decoding` debug option, `tiff-log-callbacks` test feature flag

---

index.md

jpathinformatics.org has turned into an HTTP-only redirect.  Drop the Abstract and Get PDF links, and just use the DOI link to the paper's HTML page.  That way we won't need to update for any future changes to the journal's site layout.

Update links to J Path Inform technical note

---

formats/hamamatsu/index.md

Thanks @ntrahearn for figuring this out!
Also link to NGR and NDPI ImHex patterns.

formats/hamamatsu: document how NDPI 64-bit offsets really work

---

demo/_synctiles.py

We're moving to a bucket with per-object ACLs disabled.  This is simpler to administer but requires the bucket to be manually configured with a policy allowing public reads.  `_synctiles.py` does not set a bucket policy automatically, as it does with CORS, to avoid clobbering any nuanced policy configured by the bucket owner.

synctiles: don't set explicit `public-read` ACL on objects

---

.pre-commit-config.yaml
demo/_synctiles.py
pyproject.toml

synctiles: automatically detect number of available CPUs

---

download/index.md

Those distros have a pip version too old to use the wheel, so pip must be upgraded first.

Document `pip install openslide-bin` considerations for EL 8/Ubuntu 20.04

---

.github/workflows/retile.yml

OpenSlide Python 1.4.0+ uses `openslide_python-*` per PEP 625.

workflows/retile: update for OpenSlide Python tarball rename
